# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Stacy Montemayor"
description: > # this means to ignore newlines until "email:"
   data wrangling + visualizations for storytelling

email: stacy.montemayor@gmail.com
#blog logo
logo: "/assets/images/sm_logo.jpg"
float_logo: true # true, false (default)
markdown: kramdown

# blog cover
cover: "/assets/images/cover_image.png"

name: 'Stacy Montemayor'
author: 'Stacy Montemayor'
# author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://teacupwoozy.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_username: teacupwoozy
github_username: teacupwoozy

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/teacupwoozy
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/teacupwoozy
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title:
    share_link:

  - icon:	linkedin-in
    url:	https://www.linkedin.com/in/stacymontemayor/
    desc: Connect with me on Linkedin
    share_url:
    share_title:
    share_link:

  - icon:	dev
    url:	https://dev.to/stacy
    desc:	Connect with me on dev.to
    share_url:
    share_title:
    share_link: